### ISSUE TITLE
Running gulp on fresh Windows install

### ISSUE THREAD

**Issue by Hyllesen** [Skippeh/calcrust.com-frontend#10]
Hey,

I got the project running on Ubuntu VM I have, but would like to get this running on my main Windows workspace.

Now I've installed node.js:

`node -v
v4.4.7`

However after using `npm install`, the command `gulp is not recognized as an internal or external command`.

So I tried installing gulp globally with `npm install gulp -g`.

Now I am at this point:

```
>gulp
module.js:327
    throw err;
    ^

Error: Cannot find module 'gulp-concat'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
```

I tried deleting node_modules folder and running a fresh npm install to no avail. Same issue.

**Manual solution**
The issue could be resolved by installing gulp-concat manually like so:
`npm install gulp-concat

I am looking into making this automaticly added. Possibly the package.json file.`

**Comment by Skippeh** [comment]
That's weird, i must've forgot to add it to the package.json file.

Should be fixed when you add it to package.json.

**Comment by Hyllesen** [comment]
I've sent a pull request with gulp-concat added to package.json.
