### ISSUE TITLE
Some items only have a few items shown in damageinfo

### ISSUE THREAD

**Issue by Nothing4You** [Skippeh/calcrust.com-frontend#20]
E.g. at https://www.calcrust.com/damageinfo/door.hinged.metal I can see the stats for Bone Club, Hatchet or Rock, but it doesn't list e.g. Pick Axe, even though the stone variant is listed.

**Comment by Skippeh** [comment]
It only shows weapons that deal damage.

**Comment by Nothing4You** [comment]
I see, I didn't expect that a stone could apply damage where a metal pick axe can't.
