### ISSUE TITLE
Satchel cost for Sheet Metal Door is off

### ISSUE THREAD

**Issue by Nothing4You** [Skippeh/calcrust.com-frontend#22]
Hey there,

on https://www.calcrust.com/damageinfo/door.hinged.metal it says it costs 5 satchels to blow up a sheet metal door, ingame vanilla it's 4 satchels.

**Comment by Skippeh** [comment]
That's weird... I'll look it up. Thanks.

**Comment by Skippeh** [comment]
This is fixed now.

[The commit if you're interested](https://github.com/Skippeh/calcrust.com-backend/commit/fc87072d65796a73e745d6a0dc38a16b5e217e54)

**Comment by Skippeh** [comment]
Actually, looking at it more it's still not correct. Most items are incorrect actually (atleast for weapons). Gonna look into it more.

**Comment by Skippeh** [comment]
It seems that rust applies a random amount of damage with all explosive ammo. TIL i guess. The other ammo types are accurate though, including satchel charges etc now.
