### ISSUE TITLE
Damage values for wood wall frame are incorrect

### ISSUE THREAD

**Issue by plsfixrusto** [Skippeh/calcrust.com-frontend#29]
Can only say that I've tested trying to destroy a wooden wall frame and it took around 1 dmg every 3 hits from a hatchet; so your values are incorrect. I have no idea when the change occurred but can you please update? Love your site, thanks for all the hard work!

**Comment by Skippeh** [comment]
This should be fixed now. I've tested it myself but you can verify yourself if you want to.
