### ISSUE TITLE
Create a more user-friendly landing page

### ISSUE THREAD

**Issue by Hyllesen** [Skippeh/calcrust.com-frontend#8]
When I first came to the page I spent a good 1 minute trying to figure how to get to use it. No kidding. 

![image](https://cloud.githubusercontent.com/assets/9279498/17237397/bd7819d6-5551-11e6-9d02-87a6d344e587.png)

1. I would suggest starting on the "Items & Blueprints" as landing page and make your changelog a menu item below. 

2. Also I would suggest commenting out the links to features that is not yet implemented. (Damage tables, Cooking/Smelting Calculator).

If you like these two suggestions I would love to do it. (Once I get my nodejs working -_-)

**Comment by Skippeh** [comment]
Yeah, analytics suggests the same thing from what i can tell. Any help is appreciated. :+1:

**Comment by Hyllesen** [comment]
Was curious what analytics would say too. I have created a pull request with the changes.

**Comment by Skippeh** [comment]
I've merged it. Gonna do some small fixes and some additional testing and then put it on the live site. Thanks for the help!

**Comment by Skippeh** [comment]
Pushed some additional fixes, should be fully working now.
